.\"                                      -*- nroff -*-
.\" microdc.1 - Manual page for microdc.
.\"
.\" Copyright (C) 2005, 2005 Oskar Liljeblad
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Library General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation,
.\" Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
.\"
.TH MICRODC "1" "May 6, 2005" "microdc"
.SH NAZWA
microdc - klient Direct Connect z interfejsem tekstowym
.SH SK£ADNIA
.B microdc
.RI [ OPCJE ]...
.SH OPIS
microdc jest tekstowym klientem Direct Connect, u¿ywaj±cym biblioteki
GNU Readline do komunikacji z u¿ytkownikiem. Zosta³ napisany od podstaw
i nie korzysta z ¿adnego innego programu. Pomimo wy³±cznie tekstowego
interfejsu u¿ytkownika, microdc zosta³ zaprojektowany tak, aby byæ
przyjaznym dla u¿ytkownika i prostym w obs³udze.
.SH OPCJE
Program ten wykorzystuje zwyczajn± sk³adnie poleceñ GNU, z d³ugimi
opcjami zaczynaj±cymi siê od dwóch my¶lników (--).
.TP
.B \-\-help
Pokazuje krótki opis dostêpnych opcji.
.TP
.B \-\-version
Wy¶wietla informacjê o wersji i koñczy program.
.SH ZG£ASZANIE B£ÊDÓW
B³êdy proszê zg³aszaæ na adres <\fIoskar@osk.mine.nu\fP>.
.SH AUTOR
Autorem \fBmicrodc\fP jest Oskar Liljeblad <\fIoskar@osk.mine.nu\fP>. 
Autorem polskiego t³umaczenia programu i strony podrêcznika systemowego
jest Jakub Jankowski <\fIshasta@atn.pl\fP>
.SH PRAWA AUTORSKIE
Copyright \(co 2004, 2005 Oskar Liljeblad

To jest wolne oprogramowanie; zajrzyj do ¼róde³ po warunki
rozpowszechniania. Nie ma ¯ADNEJ gwarancji, nawet domy¶lnej gwarancji
PRZYDATNO¦CI HANDLOWEJ albo PRZYDATNO¦CI DO OKRE¦LONYCH ZASTOSOWAÑ.
